name: Build, Push, and Update Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  # Docker configuration
  DOCKER_IMAGE_NAME: password-generator-app
  DOCKER_REGISTRY: docker.io # or ghcr.io for GitHub Container Registry
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # Target repo configuration
  TARGET_REPO: password-app
  TARGET_BRANCH: main
  YAML_FILE_PATH: k8s/deployment.yaml
  COMMITTER_NAME: github-actions
  COMMITTER_EMAIL: github-actions@github.com

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      # Checkout the current repo
      - name: Checkout current repo
        uses: actions/checkout@v4

      # Login to Docker registry
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      # Checkout the target repo
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: Nikhil12894/${{ env.TARGET_REPO}}
          path: target-repo
          token: ${{ secrets.PAT_TOKEN }}

      # Update the YAML file with the new image tag
      - name: Update deployment YAML
        working-directory: ./target-repo
        run: |
          # Verify file exists
          ls -la
          ls -la k8s/
          # Use sed to replace the image tag in the YAML file
          # This assumes your YAML has a line like: image: username/repo:tag
          sed -i "s|image: $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:.*|image: $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$GITHUB_SHA|" $YAML_FILE_PATH
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          cd target-repo
          git add .
          git commit -m "Add/updated generated YAML file ${{ github.event.repository.name }} with run ${{github.run_number}} ${{github.run_id}}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}